# Adapted from:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Known Flaky Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean install -DskipTests -pl common-kafka -am
      - name: Run Flaky Test
        run: mvn -pl common-kafka edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=com.cerner.common.kafka.consumer.ProcessingKafkaConsumerTest#nextRecord_fairProcessing

